title: Settings
icon: mdi:cogs
cards:
  - type: entities
    title: Ukentlig oppsett for støvsuging
    show_header_toggle: false
    entities:
      - entity: input_boolean.daily_vacuum
      - type: divider
        style:
          height: 2px
          width: 80%
          margin-left: auto
          margin-right: auto
          background: "#62717b"
      - entity: input_datetime.vacuum_time
      - entity: input_boolean.vacuum_monday
      - entity: input_boolean.vacuum_tuesday
      - entity: input_boolean.vacuum_wednesday
      - entity: input_boolean.vacuum_thursday
      - entity: input_boolean.vacuum_friday
      - entity: input_boolean.vacuum_saturday
      - entity: input_boolean.vacuum_sunday
  - type: entities
    title: Automasjoner
    entities:
      - entity: input_boolean.automate_lights
        name: Lysautomasjoner
  - type: entities
    title: Hørbart varsel
    entities:
      - entity: input_boolean.audible_alerts
  - type: entities
    title: "Settpunkt temperatur"
    entities:
      - entity: input_number.temp_setpoint_day
      - entity: input_number.temp_setpoint_night
