# #########################################################################################################
#                                     This is the newest configuration                                    #
# #########################################################################################################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Basic Configuration
homeassistant:
  name: Vennolumsvegen 82
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml
  packages: !include_dir_named packages/
  external_url: !secret external_url
  internal_url: !secret internal_url
  temperature_unit: C
  currency: NOK

# Discovery of devices ....
discovery:

# Lovelace UI Config
lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml

frontend:
  themes: !include_dir_merge_named themes

script: !include_dir_merge_named script/
scene: !include_dir_merge_list scenes/
zone: !include zone.yaml
logger:
  default: warning
  logs:
    homeassistant.core: fatal

recorder:
  purge_keep_days: 5
  commit_interval: 30
  auto_purge: true
  exclude:
    domains:
      - automation
      - updater
    entity_globs:
      - sensor.weather_*
    entities:
      - sun.sun
    event_types:
      - call_service

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  exclude:
    domains:
      - automation
      - updater
    entities:
      - sun.sun
#rawtest:
