# #########################################################################################################
#                                     This is the newest configuration                                    #
# #########################################################################################################

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Basic Configuration
homeassistant:
  # customize: !include customize.yaml
  packages: !include_dir_named packages/

# Lovelace UI Config
lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml

frontend:
  themes: !include_dir_merge_named themes/

script: !include_dir_merge_named scripts/
scene: !include_dir_merge_list scenes/
logger:
  default: warning
  logs:
    homeassistant.core: warning
    # homeassistant.components.met: debug
    # custom_components.hra_recycling: debug
    # homeassistant.components.tibber: debug

recorder:
  db_url: !secret db_url
  purge_keep_days: 5
  commit_interval: 30
  auto_purge: true
  exclude:
    domains:
      - automation
      - updater
    entity_globs:
      - sensor.weather_*
    entities:
      - sun.sun
    event_types:
      - call_service

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  exclude:
    domains:
      - automation
      - updater
    entities:
      - sun.sun
