- platform: template
  covers:
    garage_door:
      device_class: garage
      friendly_name: "Garasjeport H"
      value_template: >-
        {% if is_state('binary_sensor.door_sensor_garage_right_contact', 'on') %}
          open
        {% else %}
          closed
        {% endif %}
      open_cover:
        - condition: state
          entity_id: binary_sensor.door_sensor_garage_right_contact
          state: "off"
        - service: switch.turn_on
          target:
            entity_id: switch.smart_implant_5
      close_cover:        
        - condition: state
          entity_id: binary_sensor.door_sensor_garage_right_contact
          state: "on"
        - service: switch.turn_on
          target:
            entity_id: switch.smart_implant_5
      icon_template:  >-
        {% if is_state('binary_sensor.door_sensor_garage_right_contact', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}