# Automation based on dog trip in Gran
automation:
  - id: dogtripactivated
    alias: Dog Trip in Gran activated
    trigger:
      - platform: zone
        entity_id: person.mercedes
        zone: zone.trintom
        event: enter
    condition: []
    action:
      - delay:
          minutes: 5
      - service: input_boolean.turn_on
        entity_id: input_boolean.dog_trip_gran_activated

  - id: dogtripdeactivated
    alias: Dog Trip in Gran deactivated
    trigger:
      - platform: zone
        entity_id: person.mercedes
        zone: zone.trintom
        event: leave
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.dog_trip_gran_activated


cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: "Garasjeport H"
        value_template: >-
          {% if is_state('binary_sensor.door_sensor_garage_right_contact', 'on') %}
            open
          {% else %}
            closed
          {% endif %}
        open_cover:
          - condition: state
            entity_id: binary_sensor.door_sensor_garage_right_contact
            state: "off"
          - service: switch.turn_on
            target:
              entity_id: switch.smart_implant_5
        close_cover:        
          - condition: state
            entity_id: binary_sensor.door_sensor_garage_right_contact
            state: "on"
          - service: switch.turn_on
            target:
              entity_id: switch.smart_implant_5
        icon_template:  >-
          {% if is_state('binary_sensor.door_sensor_garage_right_contact', 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}