automation:
  - alias: Notify Day Before Matavfall
    description: Sends a notification at 18:00 the day before the date specified in sensor.matavfall
    trigger:
      - platform: time
        at: "18:00:00"
    condition:
      - condition: template
        value_template: "{{ (as_timestamp(now()) + 86400)|timestamp_custom('%Y-%m-%d') == state_attr('sensor.matavfall', 'date') }}"
    action:
      - service: notify.mobile_app_erik_sin_iphone
        data:
          message: "Reminder: Matavfall pickup is tomorrow."
          title: "Matavfall Pickup Reminder"
    mode: single

template:
  - sensor:
      - name: "Days Until Matavfall"
        state: >
          {% set matavfall_date = as_timestamp(states('sensor.matavfall')) %}
          {% set days_until = ((matavfall_date - as_timestamp(now())) // 86400)|round %}
          In {{ days_until }} days
