automation:
  - alias: Skru på lys innerst i gangen ved bevegelse
    trigger:
      - platform: state
        entity_id: binary_sensor.multisensor_gang_home_security_motion_detection
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.automate_lights
        state: "on"
    action:
      - service: light.turn_on
        target:
          entity_id:
            - light.taklampe_1_gang_pare_1
            - light.taklampe_1_gang_pare_2
            - light.taklampe_2_gang_pare_1
            - light.taklampe_2_gang_pare_2
            - light.hue_go

  - alias: Skru av lys innerst i gangen etter 10 minutter fra siste bevegelse
    trigger:
      - platform: state
        entity_id: binary_sensor.multisensor_gang_home_security_motion_detection
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.automate_lights
        state: "on"
    action:
      - delay:
          minutes: 10
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.multisensor_gang_home_security_motion_detection
            state: "off"
      - service: light.turn_off
        target:
          entity_id:
            - light.taklampe_1_gang_pare_1
            - light.taklampe_1_gang_pare_2
            - light.taklampe_2_gang_pare_1
            - light.taklampe_2_gang_pare_2
            - light.hue_go
input_boolean:
  automate_lights:
    name: Lysautomasjoner
    icon: mdi:lightbulb
