automation:
  - id: nightmode
    alias: Activate Night Mode
    trigger:
      - platform: state
        entity_id: input_boolean.night_mode
        from: "off"
        to: "on"
    action:
      - entity_id: input_boolean.day_mode
        service: input_boolean.turn_off
      - entity_id: input_boolean.party_mode
        service: input_boolean.turn_off

  - id: daymode
    alias: Activate Day Mode
    trigger:
      - platform: state
        entity_id: input_boolean.day_mode
        from: "off"
        to: "on"
    action:
      - entity_id: input_boolean.night_mode
        service: input_boolean.turn_off
      - entity_id: input_boolean.party_mode
        service: input_boolean.turn_off

  - id: partymode
    alias: Activate Party Mode
    trigger:
      - platform: state
        entity_id: input_boolean.party_mode
        from: "off"
        to: "on"
    action:
      - entity_id: input_boolean.day_mode
        service: input_boolean.turn_off
      - entity_id: input_boolean.night_mode
        service: input_boolean.turn_off

input_boolean:
  erik_hjemme:
    name: Erik Hjemme
    icon: mdi:account
  jorgen_hjemme:
    name: Jørgen Hjemme
    icon: mdi:account
  night_mode:
    name: Nattmodus
    icon: mdi:weather-night
  day_mode:
    name: Dagmodus
    icon: mdi:weather-sunset-up
  guest_mode:
    name: Gjestemodus
    icon: mdi:human-male-female
  party_mode:
    name: Partymodus
    icon: mdi:party-popper
  people_home:
    name: Hjemmemodus
    icon: mdi:home
  away_mode:
    name: Bortemodus
  vacation_mode:
    name: Feriemodus
    icon: mdi:airplane-takeoff
  dog_mode: # Dog mode
    name: Dog Mode
    icon: mdi:dog
