automation:
  - alias: Unlock Mercedes
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 6
          label: "Scene 001"
          value_raw: 0
    action:
      - service: mbapi2020.doors_unlock
        data:
          vin: !secret mercedes_vin

  - alias: Toggle Right Garage Door
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 6
          label: "Scene 002"
          value_raw: 0
    action:
      - service: cover.toggle
        entity_id: cover.garage_door

  - alias: Lock Mercedes
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 6
          label: "Scene 003"
          value_raw: 0
    action:
      - service: mbapi2020.doors_lock
        data:
          vin: !secret mercedes_vin

  - alias: Toggle light in Gang
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 6
          label: "Scene 004"
          value_raw: 0
    action:
      - service: light.toggle
        target:
          entity_id: light.gang

  - alias: Fjernkontrolltest
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 7
          label: "Scene 003"
          value_raw: 0
    action:
      - service: light.toggle
        entity_id: light.soverom
